[project]
name = "fastapi-test"
version = "0.1.0"
description = "FastAPI Learning Repo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.13",
    "uvicorn[standard]>=0.34.3",
]
